[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-bot"
version = "0.0.1"
authors = [
  { name="User", email="user@example.com" },
]
description = "A simple stock trading bot project"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
